---
title: "Team Datatepe"
sidebar: false 
---

This is our project webpage.

Please stay tuned to follow our project activities.

# Team Members

1.  [Yiğit Türkel](https://emu-hacettepe-analytics.github.io/emu430-fall2024-yigitturkel-lab/)

2.  [Firuze İpek Yıldırım](https://emu-hacettepe-analytics.github.io/emu430-fall2024-firuzeipekyildirim/)

3.  [Muhammed Uğur Çubuk](https://emu-hacettepe-analytics.github.io/emu430-fall2024-mugurcubuk/)[ ](https://tr.wikipedia.org/wiki/Fred_(1993_do%C4%9Fumlu_futbolcu))

4.  [Elif Lorasdağı](https://emu-hacettepe-analytics.github.io/emu430-fall2024-elflrsdglab/)

5.  [Hazan Fakılı](https://emu-hacettepe-analytics.github.io/emu430-fall2024-hazanfakili/)

6.  [Tutku Altay](https://emu-hacettepe-analytics.github.io/emu430-fall2024-taltaylab/)

# Project Topic

Comprehensive Analysis of Hacettepe University Engineering Faculty (2018-2024)

This project focuses on a detailed analysis of the admissions and demographic trends in the Engineering Faculty of Hacettepe University over the period from 2018 to 2024. The analysis covers several key parameters: capacities, valedictorians, gender distributions, the geographical regions from which students originate, and the number of national preferences for the faculty. By examining these aspects, the project aims to highlight shifts in student demographics, changes in gender representation, regional diversity, and the popularity of the faculty across Turkey. The findings will provide valuable insights into the evolution of admission policies and the factors influencing student choices during this period.

# Data Set

Click to see [our data set](https://docs.google.com/spreadsheets/d/1j_uFnTN_WHLdQg5khKyaxF10WOlic646JNyXT7vxPvI/edit?usp=sharing). Initially we thought of using [Thestats package](https://github.com/analyticsresearchlab/thestats) from [analyticsresearchlab/github](https://github.com/analyticsresearchlab/thestats) but it wasn't up-to-date so we decided to use [YÖK Atlas](https://yokatlas.yok.gov.tr) data by collecting them by hand (we didn't know web scrapping at that moment). This dataset consists 15 Engineering Departments of University of Hacettepe and several information for the past 7 years for each department.
